import { GitHubActions } from "github/src/client/index.mjs";

export class BaseTemplate {
	#actions;
	constructor(options = {}) {
		this.#actions = new GitHubActions();
	}

	/**
	 * If running on GitHub Actions, the footer includes a link to the workflow run URL.
	 * @function footer
	 * @returns {string} The footer content with optional GitHub Actions workflow run URL.
	 */
	get footer() {
		if (this.#actions.isGitHubActions) {
			return `> generated by: ${this.#actions.getWorkflowRunUrl()}`;
		}

		return "";
	}

	build() {
		return "";
	}
}
