version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/actions/create-pr"
      - "/.github/actions/cached-node-modules"
      - "/.github/actions/version-n-changelog"
    labels: [ ]
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
        
  - package-ecosystem: npm
    directory: /.github/actions/version-n-changelog
    labels: [ ]
    schedule:
      interval: weekly
    versioning-strategy: increase
    commit-message:
      prefix: "chore"
    groups:
      bundle-tools:
        patterns:
        - "bump-n-go"