version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: npm
    directory: /
    labels: [ ]
    schedule:
      interval: daily
    versioning-strategy: increase
    groups:
      aws-sdk:
        patterns:
        - "@aws-sdk/**"
        - "@smithy/**"
        - "aws-sdk-client-mock"
        - "aws-sdk-client-mock-jest"
      aws-cdk:
        patterns:
        - "@aws-cdk/**"
        - "aws-cdk-lib"
        - "aws-cdk"