blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/aws-powertools/actions/discussions/new
    about: Ask a general question about the project
  - name: Join Community Discord Server
    url: https://discord.gg/B8zZKbbyET
    about: "Start from the #general channel"