name: Technical debt
description: Suggest an activity to help address technical debt.
title: "Tech debt: TITLE"
labels: ["tech-debt", "triage"]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to help us proactively improve delivery velocity, safely.
  - type: textarea
    id: importance
    attributes:
      label: Why is this needed?
      description: Please help us understand the value so we can prioritize it accordingly
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: If available, please share what a good solution would look like
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.