export const BLOCKED_LABELS = ["do-not-merge", "need-issue", "need-rfc", "need-customer-feedback"];
export const FEATURE_REQUEST_LABEL = "feature-request";
export const TOP_FEATURE_REQUESTS_LIMIT = 3;
export const TOP_MOST_COMMENTED_LIMIT = 3;
export const TOP_OLDEST_LIMIT = 3;
export const TOP_LONG_RUNNING_PR_LIMIT = 3;
export const REPORT_ROADMAP_LABEL = "report-roadmap";
export const SERVICE_NAME = "reporting";
export const NO_CONTENT_AVAILABLE_DEFAULT = "Not available";
